---
title: "learningR_1"
author: "joshxie"
date: "2020/3/12"
output:
  html_document: default
  pdf_document: default
---
# R learning lecture 1
## 向量物件 


```{r}

x<-1:10
print(x)

```


```{r}

x<-11:13
print(x)

```


```{r}

x<--1:-5
print(x)

```
也可以是-1

```{r}

x<- -1.7:-5.3
print(x)

```

不足1, 不顯示

```{r}

x<-1:5
y<-x+3
print(x)
print(y)

```

每個都 + 3


```{r}

x<-1:3
y<-1:6+x
print(x)
print(y)

```

3 and 6, 6=3*k
if b=a*K?

```{r}

x<-1:4
y<-1:6+x
print(x)
print(y)
```
error!!!

## 建立 seq( ) function 
```{r}
seq(1,9)
```
from 1 to 9

```{r}
seq(1, 9, by = 2)
```

from 1 to 9, by 2

```{r}
seq(1, 9, by = pi)
```

from 1 to 9, by $\pi$ 

```{r}
seq(1, 9, by = 0.5)
```

from 1 to 9, by 0.5

```{r}
seq(1, 9, length.out = 4)
```

from 1 to 9, has four numbers.


##  c( ) function 
```{r}
baskest.NBA2016.Lin<-c(7,8,6,11,9,12)
print(baskest.NBA2016.Lin)
```

建立向量

```{r}
sum(baskest.NBA2016.Lin)
```


```{r}
max(baskest.NBA2016.Lin)
```


```{r}
min(baskest.NBA2016.Lin)
```

## prod()

```{r}
prod(1:2)
prod(1:3)
prod(1:4)
prod(1:5)
prod(1:6)
```

## cum( )

```{r}
baskest.NBA2016.Jordon<-c(10,5,9,15,7,11)
cumsum(baskest.NBA2016.Jordon)
cumprod(baskest.NBA2016.Jordon)
cummax(baskest.NBA2016.Jordon)
cummin(baskest.NBA2016.Jordon)
```

## diff( )

```{r}
baskest.NBA2016.Jordon
diff(baskest.NBA2016.Jordon)
```

差距

## 向量物件排序函數

sort(x,decreasing = <font style="color:red">FALSE</font>) 小排到大
```{r}
baskest.NBA2016.Jordon
sort(baskest.NBA2016.Jordon)
```

## sort(x,decreasing = <font style="color:red">TRUE</font>) 大排到小
```{r}
baskest.NBA2016.Jordon
sort(baskest.NBA2016.Jordon, decreasing = TRUE)
```

## rank() 排名
從小到大的排名

```{r}
baskest.NBA2016.Jordon
rank(baskest.NBA2016.Jordon)
```

## rev( ) 顛倒func
```{r}
x<-c(7,11,4,9,6)
x
rev(x)
```

## length 計算向量物件的個數

```{r}
baskest.NBA2016.Jordon
length(baskest.NBA2016.Jordon)
```


## sd 標準差 var 變異數

```{r}
sd(c(11,15,8))
var(14:16)
```








































