---
title: "lesson_R_2"
author: "謝錚奇＿D54079012"
date: "4/2/2020"
output: html_document
---

# Matrix

## create Matrix by matrix( )
```{r}
# Matrix(data, nrow = ?, ncol = ?, byrows = logical, dimnames = NULL)
# data 
# nrow : how many row
# ncol : how many colums
# byrow : logical put data in row 

# full row first
e.g.1 = matrix(1:12,nrow = 4, byrow = T)
e.g.1

# full column first
e.g.2 = matrix(1:12,nrow = 4, byrow = F)
e.g.2

```
## matrix 的屬性
```{r}
# str()
str(e.g.1)
str(e.g.2)
# nrow : how many row?
nrow(e.g.1)
nrow(e.g.2)

# ncol : how many col?
ncol(e.g.1)
ncol(e.g.2)

#is.matrix()
is.matrix(e.g.1)
is.matrix(e.g.2)

#is.array()
is.array(e.g.1)
is.array(e.g.2)
```
## create Matrix by vector
```{r}
# rbind : treat c()s as rows and bind them
r1 = c(1:6)
r2 = c(1,2)
# see rows' names!! 
rbind(r1,r2)

#
#
basket.NBA2016.Jordon = c(12,8,9,15,7,12)
basket.NBA2016.Lin = c(7,8,6,11,9,12)
NBA<- rbind(basket.NBA2016.Jordon, basket.NBA2016.Lin)
NBA
```

## get sth: Matrix[r,col]
```{r}
NBA[1,1] # from NBA get row:1,col:1

NBA[1,c(1,2,3)]# from NBA get row:1,col:1 and row:1,col:2 nd row:1,col:2 nd row:1,col:3

NBA[1, ]# get first row


NBA
NBA[,-6] # deletw 6th col

# change value
NBA1 = NBA
NBA1[,6] = c(0,0)
NBA1
```

## rows' and cols' names
```{r}
simple.matrix = matrix(1:12, nrow=3)
simple.matrix # no names
#
#
rownames(simple.matrix)
```


```{r}
#
colnames(simple.matrix)
#
#
NBA
#
rownames(NBA)
#
colnames(NBA)
```

## change rows' names
```{r}
rownames(NBA) <- c("Jordon","Lin")
colnames(NBA) <- c('1st',"snd",'3rd','4th','5th','6th')
NBA

# clear cols' names
colnames(NBA) <- NULL
NBA

# dimnames()
colnames(NBA) <- c('1st',"snd",'3rd','4th','5th','6th')
dimnames(NBA)

# find item
NBA[2,]
# or
NBA["Lin",]
```
## matrix operation
```{r}
m1.matrix <- matrix(1:12, nrow = 3)
m1.matrix

m2.matrix = m1.matrix +3 # each item +3
m2.matrix 

m3.matrix = m1.matrix -1 # each item2 -1
m3.matrix

```

## row col operations
```{r}
NBA
#
rowSums(NBA)
#
rowMeans(NBA)
```

## Transfer
```{r}
NBA
t(NBA)
```
## %*%
```{r}
m1.matrix

m1.matrix * 1:12 # 對應

m1.matrix %*% 1:4

# diag() -> diagonal
diag(m1.matrix)
diag(1, 3,3) #建立Identity Matrix
#solve() 反矩陣
#det() 行列式
```


